### ISSUE TITLE
Question: Development Activity

### ISSUE THREAD

**Issue by Geyup** [garnetius/compton#2]
First let me say thanks for forking this and putting out some commits.

As I'm sure you're aware of, compton is in much need of active development, do you think you'll be able to have more activity on this?

Thanks

**Comment by garnetius** [comment]
I don't consider **compton** a dead project. Sure, its original developers have left, but I forked it, committed few bug fixes, polished here and there, and I'd call it just "complete". I can't think of any major new features to add and what's right now satisfies me pretty well. You have to be more specific about what kind of feature(s) you would like to see in **compton**.

**Comment by Geyup** [comment]
I can't say that I'm looking for any features, just would like to see it maintained and the bugs squashed.

There are a lot of bug reports still not completed on compton...
