### ISSUE TITLE
No Shadow Around Openbox Menu

### ISSUE THREAD

**Issue by Geyup** [garnetius/compton#3]
My Specs;

Slackware 14.2 x86_64
Openbox 3.6.1
Nvidia GTX660M
nvidia-driver-352.63
xorg-server-1.18.3

I just pulled your latest from git today and installed it and noticed when I open the menu for Openbox it has no shadow being drawn around it.

Here's a screen shot showing this;

![shadow_2](https://cloud.githubusercontent.com/assets/13072581/19017957/1a1d225a-8840-11e6-8147-57a0ae0d2a37.jpg)

This is compton, now notice the shadow being drawn around it;

![shadow_1](https://cloud.githubusercontent.com/assets/13072581/19017965/2c2a853c-8840-11e6-9acb-a2de73f6ae72.jpg)

This is my config file;

[compton.txt](https://github.com/garnetius/compton/files/504733/compton.txt)

**Comment by Geyup** [comment]
I noticed there is a shadow being drawn, but very faint compared to compton;

![shadow_3](https://cloud.githubusercontent.com/assets/13072581/19018023/9f8d62a0-8841-11e6-863b-120ffe7b02ee.jpg)

**Comment by Geyup** [comment]
Here's a look at the menu in compton in front of firefox to give a better view;

![shadow_4](https://cloud.githubusercontent.com/assets/13072581/19018039/9c04229e-8842-11e6-8ada-4eb27ebe21f9.jpg)

**Comment by garnetius** [comment]
Hi @Geyup

I apologise for quite late response. I was busy with lots of other code which is not on GitHub (at least yet) and forgot to log in into my GitHub as I do once in a while.

The problem with your setup is that you are not using any new configuration directives in your config file that are supposed to be used to style my patched **compton** proprely. You can take a look at https://github.com/garnetius/steambox/blob/master/.config/compton.conf from my [STEAMbox](https://github.com/garnetius/steambox) repo for a proper configuration file example. In particular, you are looking for `shadow-menu-radius`, `shadow-menu-offset-x` and other `shadow-menu-` parameters that would allow you to adjust the appearance of popup menu shadows. I should probably edit the actual README file and document them someday. As for now, you can just take all configs from the mentioned STEAMbox repo and work your way from there.

**Comment by Geyup** [comment]
@garnetius sorry for the late reply.

For now I'm just back to the original compton, but I hope you might be more active with this fork, maybe then I'll give it a go again...

There are so many bugs that need fixing and it's sad there's no active development going on...

thanks again
